### ISSUE TITLE
There is no code.

### ISSUE THREAD

**Issue by moorepants** [WCEC-UCDavis/Energy-Data-Processing-Tools#1]
What kind of project is this?

**Comment by remcmurry** [comment]
Jason it is basically a big energy calculator we are trying to develop for
air conditioners, heat pumps etc for lab and field testing so we can
automate a lot of our data processing and standardize more of our methods
... the hope is to also allow some of the less programming savvy people
here at WCEC some tools for generating the plots they want from this data
outside of excel.  either through some sort of an ipython with interact
tools method or a gui we develop.

Cheers

Robert (Robbie) McMurry
Assistant Development Engineer, Western Cooling Efficiency Center
Minister, Davis Bike Collective (Bike Forth)
remcmurry@gmail.com
mobile: (575) 323 4561

**Comment by moorepants** [comment]
I was joking :smile:
